Adds multi contributor functions to the Investor Staking Contracts
oxen-io/eth-sn-contracts pull request #77
Opened 2024-09-04 01:46 UTC by darcys22

2024-09-19 07:44 UTC, Doy-lee requested changes

2024-09-19 07:44 UTC, Doy-lee commented on contracts/utils/TokenVestingStaking.sol
> +            if (investorServiceNodes[i - 1].contributionContract == contributionContractAddress) {
Similar stale node problem here if the contract is reset/cancelled or reused. The entry will persist and there won't be a way to get rid of it. I think we can just flush them out on claimRewards, or all these functions that interact with the contract have a modifier to groom the list.

2024-09-20 04:00 UTC, darcys22 commented on contracts/utils/TokenVestingStaking.sol
> +                if (!contributionContract.finalized() && contributedAmount > 0)
So contributedAmount here is ment to be checking if the contributions contract has been reset, so the statement here is saying 
```
if ( not finalised and not reset)
    continue // no more action needed to update our internal state
```
If it does find it finalised and reset then it goes and finds the bls key to check the staking rewards contract.

I think you are correct here with the `contribute -> reset -> contribute -> finalise` causing issues. The `contributeFunds()` function should have some more logic to handle that in the second contribute. I'm thinking all contributeFunds calls should synchronize the invesor contract with the contribution contract.

2024-09-20 04:16 UTC, darcys22 commented on contracts/utils/TokenVestingStaking.sol
> +            uint64 serviceNodeID = investorNode.serviceNodeID;
I think there might be a way to solve this by checking and syncing the investor contract whenever the investor contributes.

2024-10-08 23:07 UTC, Doy-lee commented
Issues have been addressed and merged in via https://github.com/oxen-io/eth-sn-contracts/pull/87

2024-10-08 23:07 UTC, closed without merging